project:
  type: book

book:
  title: "Random Variable untuk Pengambilan Keputusan"
  author: "Armein Z. R. Langi"
  date: now
  chapters:
    - index.qmd
    - 00-kata-pengantar.qmd
    - 01-pendahuluan-pengambilan-keputusan.qmd
    - 02-random-variable-umum.qmd
    - 03-distribusi-diskrit.qmd
    - 04-distribusi-kontinu.qmd
    - 05-random-variable-multivariat-dan-fungsi.qmd
    - 06-penutup.qmd

lang: id
format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
  typst:
    toc: true
    keep-typ: true

execute:
  echo: true
  warning: false
  message: false
